### ISSUE TITLE
Auto complete function

### ISSUE THREAD

**Issue by agch-dev** [harogaston/Sublime-Modula-2#10]
Hello,

I'm having issues with the autocomplete function. For some reason it searches the comments for words and displays them in the autocomplete dropdown which is very anoying cause it clutters the dropdown. Is there a way that I can change this? 

thanks

**Comment by harogaston** [comment]
Hi and thank you for your comments. AFAIK that functionality is not possible (maybe check with other packages to see if any of them has accomplished that). However I'll do a bit of research, if you have any new insights or feedback please let me know.

Cheers,
Gastón.

**Comment by bryant1410** [comment]
I searched a little bit, and it seems to be almost impossible: https://stackoverflow.com/questions/26531538/prevent-sublime-text-from-extracting-keywords-in-comments-for-completion

It goes beyond this package

**Comment by bryant1410** [comment]
@harogaston I think you can close this issue
