### ISSUE TITLE
Modula-2 does not have any DOWNTO syntax.

### ISSUE THREAD

**Issue by trijezdci** [harogaston/Sublime-Modula-2#12]
https://github.com/harogaston/Sublime-Modula-2/blob/9bd5077f925ac7a3edc87d45d1f872593ff7377e/for_downto.sublime-snippet#L3

This syntax is Pascal, NOT Modula-2.

Modula-2 does NOT have FOR DOWNTO syntax.

Instead, the FOR loop syntax in Modula-2 is as follows:

forStatement :=
  FOR ident ':=' constExpr TO constExpr ( BY constExpr )? DO statementSeq END
  ; 

Descending iteration is achieved by using the optional BY subclause with a negative expression.

For example

FOR i := 100 TO 0 BY -1 DO
  ...
END;

**Comment by harogaston** [comment]
Hi @trijezdci ! Are you interested in this repo? If so I can transfer ownership to you. I do not maintain this anymore since 2014 or so.

**Comment by trijezdci** [comment]
> Are you interested in this repo? If so I can transfer ownership to you. I do not maintain this anymore.

It depends.

It all comes down to the quesiton "What is the actual purpose of this repo?". The name "Sublime Modula-2" suggests the actual purpose is editing support for Sublime Text. However, I don't use Sublime Text, and I don't care about it either.

My sole interest is for Github to render sources correctly when browsing Modula-2 based projects online.

Years ago, Bitbucket and Github used a framework called Pygments to recognise and render source code. I contributed the plugin for multi-dialect Modula-2 support to Pygments and it all worked perfectly. Then Bitbucket moved away from Python, and later Github as well. With that, they also moved to other means of recognising and rendering source code.

Github's way of doing this is absolutely ridiculous. It violates just about all the best practices and design principles there are. Most notably the principle of separation of concern, meaning you design a sub-system to do just one thing and one thing only. Github is using a system called Linguist, but it doesn't have any notational system for language syntax.

Instead, Linguist uses the notations of several different editors, amongst them is the Sublime Text notation and they used your repository to pull the syntax descriptions. As a result, Github's rendering of Modula-2 sources is wrong.

To fix this, there are two possible approaches:

(1) change the description files in your repo,
(2) get github to pull the descriptions from a different repo. 

If I was to take over the repo and change the descriptions, I would want to remove everything that Linguist doesn't use. Separation of concern!!! This means, I would repurpose the repo to **no longer support Sublime Text**, but only support Linguist. In fact, I have forked your repo and already started to remove those parts which I could easily identify as being solely for the purpose of editing, such as code folding information.

However, given the name of the repo, there may well be people who use this for Sublime Text, or worse, the developers of Sublime Text may be using this and include it as third party support. In any event, if support for Sublime Text is removed, then the repo should no longer be called Sublime Modula-2, it should be called Linguist Modula-2 Support or similar.

Before this background, I am not entirely sure that taking over the repo, repurposing and renaming it would be the best approach here. It may be better to get the Linguist maintainer to switch over to my forked and modified copy.

But let me know what you think about this, now that you understand my motive and the problem I am trying to solve.

regards
benjamin

**Comment by harogaston** [comment]
Well, so, to begin with:

> "What is the actual purpose of this repo?"

It is to provide syntax highlighting for Modula-2 programming language to SublimeText2 (as it clearly reads at the beginning of the Readme.md file)

>  I don't use Sublime Text, and I don't care about it either.

Neither do I.

> My sole interest is for Github to render sources correctly when browsing Modula-2 based projects online.

Nice.

> Instead, Linguist uses the notations of several different editors, amongst them is the Sublime Text notation and they used your repository to pull the syntax descriptions. 

I guess that is on them not me then. Nobody asked.

> (1) change the description files in your repo,

PRs welcomed!

>  I would repurpose the repo to no longer support Sublime Text, but only support Linguist.

That seems wrong. Forking seems more appropriate for that scenario. Anywhere does this repo say it is a "Linguist" pluging or whatever they are called. If somebody is using it for that purpose then it is on them. That is no reason for this repo to change.

> Before this background, I am not entirely sure that taking over the repo, repurposing and renaming it would be the best approach here. It may be better to get the Linguist maintainer to switch over to my forked and modified copy.

Absolutely. 100%.

**Comment by harogaston** [comment]
Closed by inactivity.
